(function ensightenInit(){var ensightenOptions = {client: "tronc", clientId: 2115, publishPath: "chicagotribunenguxprod", isPublic:0, serverComponentLocation: "nexus.ensighten.com/tronc/chicagotribunenguxprod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/tronc/chicagotribunenguxprod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Thu Jul 27 22:44:06 GMT 2017", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.ns]||(window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={}),window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(g){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=
b.dataDefinitionIds.length,d=!0,e=0;e<a;e++){var c=b.dataDefinitions[b.dataDefinitionIds[e]];if(!c||null==c.endRegistration){d=!1;break}}d&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=g.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:g.interval||100,erLoc:g.errorLocation||c.nexus+"/error/e.gif",scLoc:g.serverComponentLocation||c.nexus+"/"+g.client+"/serverComponent.php",sjPath:g.staticJavascriptPath||
c.nexus+"/"+g.client+"/code/",alLoc:g.alertLocation||c.nexus+"/alerts/a.gif",publishPath:g.publishPath,isPublic:g.isPublic,client:g.client,clientId:g.clientId,enableTagAuditBeacon:g.enableTagAuditBeacon,scUseCacheBuster:g.scUseCacheBuster,beaconSamplingSeedValue:g.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.runRuleIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var d=
0;d<a.dependencies.length;d++)if(!1===a.dependencies[d]())return;a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,d,e,l){for(a=0;a<e.length;a++)if("DEPENDENCYNEVERAVAILABLE"===e[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),
d&&-1!==d&&c.allDeploymentIds.push(d),!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var d=(c.currSec||0)%20,b=c.options.beaconSamplingSeedValue;-1===b?a=!0:0!==d&&0===b%d&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=
function(a,b){c.ensightenVariables[a]=b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||
"")+"&lnn="+encodeURIComponent(a.lineNumber||a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=
function(){this.executionData.runTime.push(new Date);b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(d){window[ensightenOptions.ns].reportException(d)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(c.runDeploymentIds.push(this.deploymentId),c.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&
-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunRuleIds=function(){return c.runRuleIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=
function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);
this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=
a;return b};b.insertScript=function(a,d,e,l){var h,f=document.getElementsByTagName("script");l=void 0!==l?l:!0;if(void 0!==d?d:1)for(h=0;h<f.length;h++)if(f[h].src===a&&f[h].readyState&&/loaded|complete/.test(f[h].readyState))return;if(e){e=1==e&&"object"==typeof b.scDataObj?b.scDataObj:e;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));d=window.location.href;"object"===typeof e&&e.PageID&&(d=e.PageID,delete e.PageID);if("object"===typeof e)for(h in e){h=~d.indexOf("#")?d.slice(d.indexOf("#"),
d.length):"";d=d.slice(0,h.length?d.length-h.length:d.length);d+=~d.indexOf("?")?"&":"?";for(k in e)d+=k+"="+e[k]+"&";d=d.slice(0,-1)+h;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(d)}(function(a,b,d){var e=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in e){if(!e[0]){setTimeout(arguments.callee,25);return}e=e[0]}var a=b.createElement("script");a.src=d;a.onload=a.onerror=function(){this.addEventListener&&
(this.readyState="loaded")};e.insertBefore(a,e.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,e){var d=document.getElementsByTagName("script"),c;e=d[0];for(c=0;c<d.length;c++)if(d[c].src===a&&d[c].readyState&&/loaded|complete/.test(d[c].readyState))try{b()}catch(f){window[ensightenOptions.ns].reportException(f)}finally{return}d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;d.onerror=function(){this.addEventListener&&(this.readyState="loaded")};
d.onload=d.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(f){window[ensightenOptions.ns].reportException(f)}}};e.parentNode.insertBefore(d,e)};b.unobtrusiveAddEvent=function(a,b,e){try{var d=a[b]?a[b]:function(){};a[b]=function(){e.apply(this,arguments);return d.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};
b.anonymous=function(a,d){return function(){try{b.currentRuleId=d?d:"anonymous",a()}catch(e){window[ensightenOptions.ns].reportException(e)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||
-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||
-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,d,e){if("function"===
typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var d,e=0;e<a.length;++e)if(d=b.getRule(parseInt(a[e],10)),!d||!d.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,d,e,l,h){var f=[];if(!c.checkForInvalidDependencies(d,l,e,h)){f.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});
if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,d,e,l,h){var f=[];if(!c.checkForInvalidDependencies(d,l,e,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});f.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,d,e,l,h){var f=[];if(!c.checkForInvalidDependencies(d,l,e,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});f.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,d,e,l,h){var f=[];
if(!c.checkForInvalidDependencies(d,l,e,h)){f.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});f.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,d,e,l,h){var f=[];if(!c.checkForInvalidDependencies(d,l,e,h)){f.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});
f.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,d,e,l,h){var f=[];if(!c.checkForInvalidDependencies(d,l,e,h)){f.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});f.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===
typeof a)a=new b.Rule({id:d||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var d=a.length,e=0;e<d;e++){var c=a[e];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,f=b.dataDefinitionIds.length,g=0;g<f;g++)if(b.dataDefinitionIds[g]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=
!0;p()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,d){var e=b.dataDefinitions[d];e||(e=new b.DataDefinition(d,a),b.dataDefinitions[d]=e);e.startRegistrationTime||(e.startRegistration(),e.registrationFn(),e.endRegistration());b.pageSpecificDataDefinitionsSet&&
p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,
e=a.length;b<e;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=
function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,e=!1;return{add:function(d){b&&!e?d():"function"==typeof d&&(a[a.length]=d)},exec:function(){e=!0;do{var d=a;a=[];b=!0;for(var c=0;c<d.length;c++)try{d[c].call(window)}catch(f){window[ensightenOptions.ns].reportException(f)}}while(0<
a.length);e=!1},haveRun:function(){return b}}};b.new_fArray=function(){return r()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=
b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(d){setTimeout(arguments.callee,
15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],d,e,l,h,f=0;f<c.ruleList.length;++f)e=c.ruleList[f],l=e.executionData.hasRun?"1":"0",h=e.deploymentId.toString()+"|"+e.id.toString()+"|"+l,a.push(h);d="["+a.join(";")+
"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(g.client)+"/"+encodeURIComponent(g.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(g.clientId)+"&data="+d+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(q){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions),"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&
window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var g=window.performance;if(g){var g=g.timing||{},m=g.navigationStart||0,n={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",
requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var p="&ns="+encodeURIComponent(g.navigationStart);for(var c in n)if(void 0!==g[c]){var b=g[c]-m;p+="&"+n[c]+"="+(0<b?encodeURIComponent(b):0)}else p+="&"+n[c]+"=-1";window[ensightenOptions.ns].timing=p;c=ensightenOptions.nexus||"nexus.ensighten.com";g=ensightenOptions.staticJavascriptPath||"";p=g.indexOf(".com/");m=g.indexOf("/code/");g=g.substring(p+4,m)+"/perf.rnc";
g+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+c+g)}}}));
		
window[ensightenOptions.ns].ensEvent||(window[ensightenOptions.ns].ensEvent=function(q,w){var h={queue:{},pollQueue:{},pushTrigger:function(a,c){if("[object Array]"===Object.prototype.toString.call(a)){for(var g=0;g<a.length;g++)h.pushTrigger(a[g],c);return!0}if("string"!=typeof a)return!1;this.queue[a]=this.queue[a]||{fn:[]};"function"==typeof c&&this.queue[a].fn.push(c);return!0},callTrigger:function(a,c,g){if("string"!=typeof a)return!1;a=h.queue[a];if("object"==typeof a&&a.fn&&a.fn.length&&(0!=
a.fireOnFirstSet&&c==w||c!=w&&0!=a.fireOnUpdate))for(c=0;c<a.fn.length;c++)a.fn[c].call(this)},setPollOptions:function(a,c,g){this.queue[a]=this.queue[a]||{fn:[]};this.queue[a].fireOnFirstSet=c;this.queue[a].fireOnUpdate=g},callPoll:function(a,c,g,q,r){if("string"==typeof a&&c&&c.length&&!(1>c.length)){for(var n=0;n<c.length;n++)h.setPollOptions(c[n],q,r);h.pushWatch(a,c,g)}},pushWatch:function(a,c,g){this.pollQueue[a]||(this.pollQueue[a]={previousVal:w,eventArr:[],valueFn:g});this.pollQueue[a].eventArr=
this.pollQueue[a].eventArr.concat(c);this.pollQueue[a].valueFn=g},globalWatch:function(){setInterval(function(){for(var a in h.pollQueue){var c=h.pollQueue[a],g=c.valueFn(a);if(c.previousVal!==g){for(var n=0;n<c.eventArr.length;n++)h.callTrigger.call(q,c.eventArr[n],c.previousVal,g);h.pollQueue[a].previousVal=g}}},500)}};h.globalWatch();return{add:function(a,c){return h.pushTrigger(a,c)},get:function(a){return h.queue[a]},trigger:function(a,c){return h.callTrigger.call(c||q,a)},poll:function(a,c,
g,n,r){r=r||q[ensightenOptions.ns].data.resolve;return h.callPoll(a,c,r,g,n)}}}(window),function(q,w,h){w[q]=h()}("qwery",window[ensightenOptions.ns],function(){function q(){this.c={}}function w(b){return H.g(b)||H.s(b,"(^|\\s+)"+b+"(\\s+|$)",1)}function h(b,d){for(var e=0,f=b.length;e<f;e++)d(b[e])}function a(b){for(var d=[],e=0,f=b.length;e<f;++e)k(b[e])?d=d.concat(b[e]):d[d.length]=b[e];return d}function c(b){for(var d=0,e=b.length,f=[];d<e;d++)f[d]=b[d];return f}function g(b){for(;(b=b.previousSibling)&&
1!=b.nodeType;);return b}function n(b,d,e,f,a,l,k,c,g,h,t){var I,B,m;if(1!==this.nodeType||d&&"*"!==d&&this.tagName&&this.tagName.toLowerCase()!==d||e&&(I=e.match(Q))&&I[1]!==this.id)return!1;if(e&&(m=e.match(R)))for(b=m.length;b--;)if(!w(m[b].slice(1)).test(this.className))return!1;if(g&&u.pseudos[g]&&!u.pseudos[g](this,t))return!1;if(f&&!k)for(B in g=this.attributes,g)if(Object.prototype.hasOwnProperty.call(g,B)&&(g[B].name||B)==a)return this;return f&&!y(l,S(this,a)||"",k)?!1:this}function r(b){return J.g(b)||
J.s(b,b.replace(T,"\\$1"))}function y(b,d,e){switch(b){case "=":return d==e;case "^=":return d.match(x.g("^="+e)||x.s("^="+e,"^"+r(e),1));case "$=":return d.match(x.g("$="+e)||x.s("$="+e,r(e)+"$",1));case "*=":return d.match(x.g(e)||x.s(e,r(e),1));case "~=":return d.match(x.g("~="+e)||x.s("~="+e,"(?:^|\\s+)"+r(e)+"(?:\\s+|$)",1));case "|=":return d.match(x.g("|="+e)||x.s("|="+e,"^"+r(e)+"(-|$)",1))}return 0}function p(b,d){var e=[],f=[],a,l,k,c,g,m=d,t=C.g(b)||C.s(b,b.split(K)),u=b.match(L);if(!t.length)return e;
l=(t=t.slice(0)).pop();t.length&&(a=t[t.length-1].match(M))&&(m=N(d,a[1]));if(!m)return e;c=l.match(E);k=m!==d&&9!==m.nodeType&&u&&/^[+~]$/.test(u[u.length-1])?function(b){for(;m=m.nextSibling;)1==m.nodeType&&(c[1]?c[1]==m.tagName.toLowerCase():1)&&(b[b.length]=m);return b}([]):m.getElementsByTagName(c[1]||"*");a=0;for(l=k.length;a<l;a++)if(g=n.apply(k[a],c))e[e.length]=g;if(!t.length)return e;h(e,function(b){v(b,t,u)&&(f[f.length]=b)});return f}function v(b,d,e,a){function l(b,a,c){for(;c=U[e[a]](c,
b);)if(f(c)&&n.apply(c,d[a].match(E)))if(a){if(k=l(c,a-1,c))return k}else return c}var k;return(k=l(b,d.length-1,b))&&(!a||z(k,a))}function f(b,d){return b&&"object"===typeof b&&(d=b.nodeType)&&(1==d||9==d)}function l(b){var d=[],e,f;e=0;a:for(;e<b.length;++e){for(f=0;f<d.length;++f)if(d[f]==b[e])continue a;d[d.length]=b[e]}return d}function k(b){return"object"===typeof b&&isFinite(b.length)}function N(b,d,e){return 9===b.nodeType?b.getElementById(d):b.ownerDocument&&((e=b.ownerDocument.getElementById(d))&&
z(e,b)&&e||!z(b,b.ownerDocument)&&F('[id="'+d+'"]',b)[0])}function u(b,d){var e,l,g;g=d?"string"==typeof d?u(d)[0]:!d.nodeType&&k(d)?d[0]:d:m;if(!g||!b)return[];if(b===window||f(b))return!d||b!==window&&f(g)&&z(b,g)?[b]:[];if(b&&k(b))return a(b);if(e=b.match(V)){if(e[1])return(l=N(g,e[1]))?[l]:[];if(e[2])return c(g.getElementsByTagName(e[2]));if(W&&e[3])return c(g.getElementsByClassName(e[3]))}return F(b,g)}function t(b,d){return function(e){var f,a;O.test(e)?9!==b.nodeType&&((a=f=b.getAttribute("id"))||
b.setAttribute("id",a="__qwerymeupscotty"),d(b.parentNode||b,'[id="'+a+'"]'+e,!0),f||b.removeAttribute("id")):e.length&&d(b,e,!1)}}var m=document,D=m.documentElement,F,Q=/#([\w\-]+)/,R=/\.[\w\-]+/g,M=/^#([\w\-]+)$/,X=/^([\w]+)?\.([\w\-]+)$/,O=/(^|,)\s*[>~+]/,Y=/^\s+|\s*([,\s\+\~>]|$)\s*/g,A=/[\s\>\+\~]/,P=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,T=/([.*+?\^=!:${}()|\[\]\/\\])/g,V=new RegExp(M.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),L=new RegExp("("+A.source+
")"+P.source,"g"),K=new RegExp(A.source+P.source),E=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),U={" ":function(b){return b&&b!==D&&b.parentNode},">":function(b,d){return b&&b.parentNode==d.parentNode&&b.parentNode},"~":function(b){return b&&b.previousSibling},"+":function(b,d,e,f){return b?(e=g(b))&&(f=g(d))&&e==f&&e:!1}};
q.prototype={g:function(b){return this.c[b]||void 0},s:function(b,d,e){d=e?new RegExp(d):d;return this.c[b]=d}};var H=new q,J=new q,x=new q,C=new q,z="compareDocumentPosition"in D?function(b,d){return 16==(d.compareDocumentPosition(b)&16)}:"contains"in D?function(b,d){d=9===d.nodeType||d==window?D:d;return d!==b&&d.contains(b)}:function(b,d){for(;b=b.parentNode;)if(b===d)return 1;return 0},S=function(){var b=m.createElement("p");return(b.innerHTML='<a href="#x">x</a>',"#x"!=b.firstChild.getAttribute("href"))?
function(b,e){return"class"===e?b.className:"href"===e||"src"===e?b.getAttribute(e,2):b.getAttribute(e)}:function(b,e){return b.getAttribute(e)}}(),W=!!m.getElementsByClassName,Z=m.querySelector&&m.querySelectorAll,aa=function(b,d){var e=[],f,a;try{if(9===d.nodeType||!O.test(b))return c(d.querySelectorAll(b));h(f=b.split(","),t(d,function(b,d){a=b.querySelectorAll(d);1==a.length?e[e.length]=a.item(0):a.length&&(e=e.concat(c(a)))}));return 1<f.length&&1<e.length?l(e):e}catch(ba){}return G(b,d)},G=
function(b,d){var e=[],f,a,c,k;b=b.replace(Y,"$1");if(f=b.match(X)){k=w(f[2]);f=d.getElementsByTagName(f[1]||"*");a=0;for(c=f.length;a<c;a++)k.test(f[a].className)&&(e[e.length]=f[a]);return e}h(f=b.split(","),t(d,function(b,f,l){k=p(f,b);a=0;for(c=k.length;a<c;a++)if(9===b.nodeType||l||z(k[a],d))e[e.length]=k[a]}));return 1<f.length&&1<e.length?l(e):e},A=function(b){"undefined"!==typeof b.useNativeQSA&&(F=b.useNativeQSA?Z?aa:G:G)};A({useNativeQSA:!0});u.configure=A;u.uniq=l;u.is=function(b,d,e){if(f(d))return b==
d;if(k(d))return!!~a(d).indexOf(b);for(var l=d.split(","),c;d=l.pop();)if(c=C.g(d)||C.s(d,d.split(K)),d=d.match(L),c=c.slice(0),n.apply(b,c.pop().match(E))&&(!c.length||v(b,c,d,e)))return!0;return!1};u.pseudos={};return u}),function(){function q(f,a,c){var l;n||(n=window[ensightenOptions.ns].qwery);l=n;if((l=l.call(c,a,c))&&0<l.length){if("_root"==a)f=c;else if(f===c)f=void 0;else{b:{for(var k=l.length,g=0;g<k;g++)if(f===l[g]){l=!0;break b}l=!1}l||(f.parentNode?(r++,f=q(f.parentNode,a,c)):f=void 0)}return f}return!1}
function w(f,a,c,g){p[f.id]||(p[f.id]={});p[f.id][a]||(p[f.id][a]={});p[f.id][a][c]||(p[f.id][a][c]=[]);p[f.id][a][c].push(g)}function h(a,c,g,h){if(h||g)if(h)for(var f=0;f<p[a.id][c][g].length;f++){if(p[a.id][c][g][f]===h){p[a.id][c][g].pop(f,1);break}}else delete p[a.id][c][g];else p[a.id][c]={}}function a(a,c,k){if(p[a][k]){var f=c.target||c.srcElement,l,h,m={},n=h=0;r=0;for(l in p[a][k])p[a][k].hasOwnProperty(l)&&(h=q(f,l,v[a].element))&&g.matchesEvent(k,v[a].element,h,"_root"==l,c)&&(r++,p[a][k][l].match=
h,m[r]=p[a][k][l]);c.stopPropagation=function(){c.cancelBubble=!0};for(h=0;h<=r;h++)if(m[h])for(n=0;n<m[h].length;n++){if(!1===m[h][n].call(m[h].match,c)){g.cancel(c);return}if(c.cancelBubble)return}}}function c(f,c,k,n){function l(c){return function(f){a(t,f,c)}}f instanceof Array||(f=[f]);k||"function"!=typeof c||(k=c,c="_root");var t=this.id,m;for(m=0;m<f.length;m++)p[t]&&p[t][f[m]]||g.addEvent(this,f[m],l(f[m])),n?h(this,f[m],c,k):w(this,f[m],c,k);return this}function g(a,c,k,h){if("string"==
typeof a&&"function"==typeof c||"string"==typeof c)g(document).on(a,c,k,h||!1);if(!(this instanceof g)){for(var f in v)if(v[f].element===a)return v[f];y++;v[y]=new g(a,y);v[y]._on=v[y].on;v[y].on=function(a,c,f,g){var h="function"==typeof c?c:f;if("function"==typeof c?f:g)a=[a],"string"==typeof c&&a.push(c),a.push(function(a){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return a.call(this);"undefined"!=typeof c.preventDefault?
c.preventDefault():c.returnValue=!1;a.call(this)}}(h)),this._on.apply(this,a);else return this._on.call(this,a,c,f)};return v[y]}this.element=a;this.id=c}var n,r=0,y=0,p={},v={};g.prototype.on=function(a,g,h){return c.call(this,a,g,h)};g.prototype.off=function(a,g,h){return c.call(this,a,g,h,!0)};g.cancel=function(a){a.preventDefault();a.stopPropagation()};g.addEvent=function(a,c,g){a.element.addEventListener(c,g,"blur"==c||"focus"==c)};g.matchesEvent=function(){return!0};g.load=function(a){setTimeout(function(a,
c){return function(){if(a.nodeName&&"a"==a.nodeName.toLowerCase()){if(c&&/^javascript\s*\:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(a,a.href||""),750)};window[ensightenOptions.ns].Delegate=g}(),function(q){var w=q.addEvent;q.addEvent=function(h,a,c){if(h.element.addEventListener)return w(h,a,c);"focus"==a&&(a="focusin");"blur"==a&&(a="focusout");h.element.attachEvent("on"+a,c)};q.cancel=function(h){h.preventDefault&&h.preventDefault();h.stopPropagation&&
h.stopPropagation();h.returnValue=!1;h.cancelBubble=!0}}(window[ensightenOptions.ns].Delegate),window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate);Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;!function(e,n,t,a){e.twq||(a=e.twq=function(){a.exe?a.exe.apply(a,arguments):a.queue.push(arguments)},a.version="1",a.queue=[]);if(!Bootstrapper.dtv&&(location.hash+location.search).indexOf("disable-twitter")<0)setTimeout(function(){t=n.createElement("script"),t.async=!0,t.src="//static.ads-twitter.com/uwt.js",n.head.appendChild(t)},3E3)}(window,document)},1762180,449601);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(window.trb||(window.trb={})).fbp=function(i,e){if(!Bootstrapper.dtv&&(location.hash+location.search).indexOf("disable-fbp")<0){var d=document,r=d.referrer,p="https://www.facebook.com/tr/?id\x3d"+i+"\x26ev\x3d"+e+"\x26ts\x3d"+Date.now()+"\x26v\x3d2.5.0\x26if\x3d"+(top!==window),pl=p.length,u="\x26dl\x3d"+encodeURIComponent(location.href),ul=u.length,l="\x26rl\x3d"+
(r?encodeURIComponent(r):"");if(pl+ul<2048){p+=u;pl+=ul}if(pl+l.length<2048)p+=l;(new Image).src=p}}},1724109,[1684605],412366,[393988]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version="2.0";n.queue=[];if(!Bootstrapper.dtv&&(location.hash+location.search).indexOf("disable-fbq")<0)setTimeout(function(){t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)},3E3)}(window,document,"script","https://connect.facebook.net/en_US/fbevents.js")},1684624,[1684605],414934,[393988]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;function bx(){setTimeout(function(){var e=document.createElement("script");e.async=true;e.src="//tag.bounceexchange.com/2051/i.js";document.head.appendChild(e)})}var l;if(!Bootstrapper.dtv&&((l=location.hash+location.search).indexOf("disable-bouncex")<0&&l.indexOf("adzone\x3d")<0||l.indexOf("enable-bouncex")>=0))window.trb&&trb.run?trb.run.push(bx):bx()},1935485,
[1684605],394101,[393988]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.Cookies=function(){return{domain:location.hostname,get:function(b,f){for(var c=document.cookie.split(";"),a=0;a<c.length;a++){var d=c[a].replace(/^\s+/,"").split("\x3d");if(d[0]==b)return f?d[1]:decodeURIComponent(d[1])}return""},set:function(b,f,c){document.cookie=b+"\x3d"+encodeURIComponent(f)+(c?";expires\x3d"+c:"")+";path\x3d/;domain\x3d"+this.domain;return this.get(b)==
f},test:function(b){return this.get(b)?!0:!1}}}();Bootstrapper.cookieSync=function(){var b={domains:[]},f={};b.localCookieName="psync_uuid";b.remoteCookieName="psync_uuid";b.generateUUID=function(){var c="",a;for(a=0;32>a;a++){var b=16*Math.random()|0;if(8==a||12==a||16==a||20==a)c+="-";c+=(12==a?4:16==a?b&3|8:b).toString(16)}return c};b.readSingleDomain=function(c,a,d){c=c||function(){};d=d||b.remoteCookieName;var e="cookieSync"+Math.random().toString().slice(2,10);a||c(!1);Bootstrapper.cookieSync[e]=
function(a){return function(b){(b=b.cookies[a])?c(b):c(!1)}}(d);Bootstrapper.insertScript(a+"/content?format\x3djsonp\x26output\x3dcookies\x26callback\x3dwindow.Bootstrapper.cookieSync."+e,!1)};b.readMultipleDomains=function(c,a,d){a=a||b.domains;d=d||b.remoteCookieName;var e=a.shift();a=function(a,d){return function(e){e?c(e):0==a.length?c(!1):b.readMultipleDomains(c,a,d)}}(a,d);b.readSingleDomain(a,e,d)};b.pushCookie=function(c,a,d){a=a||b.remoteCookieName;Bootstrapper.imageRequest(c+"/no-content?cw_"+
a+"\x3d"+d)};f.setDomains=function(c){b.domains=c};f.syncCookies=function(c,a,d){var e,f;a=a||b.domains;d=d||b.remoteCookieName;c=c||function(){};var h=function(a,d){var g=a.slice();return function(a){if(a)e=a,Bootstrapper.Cookies.set(b.localCookieName,e),c(a);else{e=b.generateUUID();for(a=0;a<g.length;a++)f=g[a],b.pushCookie(f,d,e);c(!1)}}}(a,d);(e=Bootstrapper.Cookies.get(b.localCookieName))?c(e):b.readMultipleDomains(h,a,d)};return f}()},2047898,470723);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(!Bootstrapper.dtv&&(location.hash+location.search).indexOf("disable-trueanthem")<0)setTimeout(function(){var s=document.createElement("script");s.src="//tru.am/scripts/ta-pagesocial-sdk.js";s.async=true;s.addEventListener("load",function(){TRUE_ANTHEM.configure("927")},false);document.head.appendChild(s)},3E3)},1689342,[1684605],418678,[393988]);
Bootstrapper.bindDependencyDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(!Bootstrapper.dtv&&(location.hash+location.search).indexOf("disable-retentionscience")<0)setTimeout(function(){var r=window._rsq||(_rsq=[]),t=setTimeout(c,5E3),d;r.push(["_setSiteId","241"]);r.push(["_enableOnsite"]);((window.trb||(trb={})).registration||(trb.registration=[])).push({user:c});function c(u){if(d)return;else{d=1;clearTimeout(t)}var e=u&&(e=u.getEmailAddress())&&
e.toLowerCase()||"";r.push(["_setUserId",e]);r.push(["_setUserEmail",e]);if(trb.data&&trb.data.page&&trb.data.page.metrics&&trb.data.page.metrics.contentId)r.push(["_addItem",{"id":trb.data.page.metrics.contentId}]);r.push(["_track"]);var s=document.createElement("script");s.async=true;s.src="//d1stxfv94hrhia.cloudfront.net/waves/v2/w.js";(document.head||document.body).appendChild(s)}},3E3)},1684625,[1684605],393932,[393988]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;twq("init","nuumy");twq("track","PageView")},1759245,[1762180],449215,[449601]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;fbq("init","1757361571160924");fbq("track","PageView");if(!Bootstrapper.dtv)setTimeout(function(){var p=trb.data&&trb.data.page;if(p&&p.slug&&p.sectionPath.indexOf("/entertainment/theater/")==0)trb.fbp("1566982596930557","Purchase");(trb.metering||(trb.metering=[])).push({status:function(d){if(d.matchedRule&&d.matchedRule.b&&d.matchedRule.l)trb.fbp("1757361571160924",
"AddToWishlist")}})},4E3)},1724149,[1724109,1684624],412367,[412366,414934]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(!Bootstrapper.dtv&&(location.hash+location.search).indexOf("disable-keywee")<0)setTimeout(function(){var s=document.createElement("script");s.src="//dc8xl0ndzn2cb.cloudfront.net/js/"+trb.data.page.metrics.siteName+"/v2/"+((location.hash+location.search).indexOf("trb_debug")>-1?"keywee.js":"keywee.min.js");s.async=true;document.head.appendChild(s)},3E3)},1764150,450260);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(location.href.indexOf("disable-pulse")==-1&&Bootstrapper.cookieSync)setTimeout(function(){Bootstrapper.cookieSync.setDomains(["//activate.chicagotribune.com","//activate.latimes.com","//activate.tronc.com"]);Bootstrapper.cookieSync.syncCookies()})},2047903,[2047898],475665,[470723]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(-1==location.href.indexOf("disable-pulse")){var send=function(a,b,e,f){var d=window.localStorage&&localStorage.getItem("kxkuid"),c=trb.cookie.get("pch"),g=trb.cookie.get("s_fid");b="?pulse1\x3d"+a.eVar35+"\x26pulse3\x3d"+a.server+b;a.eVar34&&(b+="\x26pulse4\x3d"+a.eVar34);a.eVar21&&(b+="\x26pulse5\x3d"+a.eVar21);referrerVar&&(b+=referrerVar);a.eVar23&&(b+="\x26pulse16\x3d"+
a.eVar23);a.eVar20&&(b+="\x26pulse60\x3d"+a.eVar20);g&&(b+="\x26pulse76\x3d"+g);a.prop46&&(b+="\x26pulse92\x3d"+encodeURIComponent(a.prop46));a.prop45&&(b+="\x26pulse124\x3d"+a.prop45);b+="\x26pulse2\x3d"+encodeURIComponent(a.pageURL)+"\x26pulse125\x3d"+exop+platformVar+"\x26pei\x3d"+f+"\x26pbrd\x3d"+metrics.pbrd+"\x26pxlid\x3d"+pageViewId+"\x26cb\x3d"+cb++;0>b.indexOf("pch\x3d")&&(b+=c?"\x26pch\x3d4\x26prefch\x3d"+c:referrer?"\x26pch\x3d5\x26prefch\x3d5":"\x26pch\x3d9\x26prefch\x3d9");e&&(b+="\x26pcid\x3d"+
e);d&&(b+="\x26pdcoid\x3d"+d);(new Image).src="https://activate."+prdomain+"/no-content"+b},cb=0,fssorid,metrics=trb.data.metrics,prdomain=metrics.prdomain,hostname=location.hostname,referrer=document.referrer,referrerVar=referrer&&"\x26pulse15\x3d"+encodeURIComponent(referrer),domainIndex=hostname.lastIndexOf(prdomain),platformVar=-1<domainIndex&&domainIndex+prdomain.length==hostname.length?"\x26pulse93\x3d1":"\x26pulse93\x3d2",pageViewId=metrics.pvid||Date.now()+"_"+Math.floor(1E9*Math.random()),
exop=trb.exopid?"true":trb.data.page&&trb.data.page.articleType&&-1<document.cookie.indexOf("xop\x3d0")?"control":"false",first=!0;(trb.dpl||(trb.dpl=[])).push({callback:function(a){var b="";a.prop62&&(b+="\x26pulse6\x3d"+a.prop62);a.prop33&&(b+="\x26pulse7\x3d"+a.prop33);a.prop34&&(b+="\x26pulse8\x3d"+a.prop34);a.eVar4&&(b+="\x26pulse9\x3d"+a.eVar4);a.eVar5&&(b+="\x26pulse10\x3d"+a.eVar5);a.eVar6&&(b+="\x26pulse11\x3d"+a.eVar6);a.eVar7&&(b+="\x26pulse12\x3d"+a.eVar7);a.eVar8&&(b+="\x26pulse13\x3d"+
a.eVar8);a.eVar10&&(b+="\x26pulse14\x3d"+a.eVar10);a.eVar37&&(b+="\x26pulse17\x3d"+a.eVar37);a.eVar38&&(b+="\x26pulse18\x3d"+a.eVar38);a.eVar39&&(b+="\x26pulse19\x3d"+a.eVar39);a.prop21&&(b+="\x26pulse20\x3d"+a.prop21);a.campaign&&(b+="\x26pulse21\x3d"+a.campaign);a.eVar64&&(b+="\x26pulse22\x3d"+a.eVar64);a.prop44&&(b+="\x26pulse25\x3d"+a.prop44);a.prop64&&(b+="\x26pulse26\x3d"+a.prop64);a.prop59&&(b+="\x26pulse27\x3d"+a.prop59);a.prop63&&(b+="\x26pulse28\x3d"+a.prop63);a.prop3&&(b+="\x26pulse29\x3d"+
a.prop3);a.prop22&&(b+="\x26pulse30\x3d"+a.prop22);a.prop23&&(b+="\x26pulse31\x3d"+a.prop23);a.eVar11&&(b+="\x26pulse32\x3d"+a.eVar11);a.prop32&&(b+="\x26pulse33\x3d"+a.prop32);a.prop36&&(b+="\x26pulse34\x3d"+a.prop36);a.prop37&&(b+="\x26pulse35\x3d"+a.prop37);a.prop51&&(b+="\x26pulse36\x3d"+a.prop51);a.prop58&&(b+="\x26pulse37\x3d"+a.prop58);a.eVar32&&(b+="\x26pulse38\x3d"+a.eVar32);a.events&&(-1<a.events.indexOf("event52")||-1<a.events.indexOf("event67"))&&(b+="\x26pulse41\x3dtrue");a.eVar62&&(b+=
"\x26pulse47\x3d"+a.eVar62);a.eVar65&&(b+="\x26pulse48\x3d"+a.eVar65);a.eVar66&&(b+="\x26pulse49\x3d"+a.eVar66);a.eVar67&&(b+="\x26pulse50\x3d"+a.eVar67);a.eVar55&&(b+="\x26pulse51\x3d"+a.eVar55);a.eVar33&&(b+="\x26pulse54\x3d"+a.eVar33);a.eVar1&&(b+="\x26pulse56\x3d"+a.eVar1);a.eVar2&&(b+="\x26pulse57\x3d"+a.eVar2);a.eVar14&&(b+="\x26pulse58\x3d"+a.eVar14);a.eVar19&&(b+="\x26pulse59\x3d"+a.eVar19);a.eVar25&&(b+="\x26pulse61\x3d"+a.eVar25);a.eVar27&&(b+="\x26pulse62\x3d"+a.eVar27);a.eVar28&&(b+="\x26pulse63\x3d"+
a.eVar28);a.eVar29&&(b+="\x26pulse64\x3d"+a.eVar29);a.eVar30&&(b+="\x26pulse65\x3d"+a.eVar30);a.eVar47&&(b+="\x26pulse66\x3d"+a.eVar47);a.eVar49&&(b+="\x26pulse67\x3d"+a.eVar49);a.eVar53&&(b+="\x26pulse68\x3d"+a.eVar53);a.eVar54&&(b+="\x26pulse69\x3d"+a.eVar54);a.eVar56&&(b+="\x26pulse70\x3d"+a.eVar56);a.eVar57&&(b+="\x26pulse71\x3d"+a.eVar57);a.eVar58&&(b+="\x26pulse72\x3d"+a.eVar58);a.eVar59&&(b+="\x26pulse73\x3d"+encodeURI(a.eVar59));a.eVar60&&(b+="\x26pulse74\x3d"+a.eVar60);a.eVar61&&(b+="\x26pulse75\x3d"+
a.eVar61);if(a.events)for(var e=0,f=a.events.split(","),d,c,g;e<f.length;e++)if(d=f[e])c=d.indexOf("\x3d"),g=parseInt(-1<c?d.substring(5,c):d.substr(5)),isNaN(g)||(b+="\x26pulse"+(1E3+g)+"\x3d"+(-1<c&&encodeURIComponent(d.substr(c+1))||"true"));a.list1&&(b+="\x26pulse77\x3d"+a.list1);a.pe&&(b+="\x26pulse78\x3d"+a.pe);a.linkName&&(b+="\x26pulse79\x3d"+a.linkName);a.prop39&&(b+="\x26pulse80\x3d"+a.prop39);a.prop40&&(b+="\x26pulse81\x3d"+a.prop40);a.prop57&&(b+="\x26pulse82\x3d"+a.prop57);a.eVar68&&
(b+="\x26pulse94\x3d"+a.eVar68);send(a,b,a.prop28,"t"==a.source?"2":"3");first&&(first=!first,setTimeout(function(){var a=trb.dpp,d=trb.dpp={push:function(a){if(a&&"object"==typeof a){var d=trb.dpl.data&&trb.dpl.data[0];if(d){var c=function(){b=a.pulse6?"":"\x26pulse6\x3d"+(e?"signed-in":"signed-out");if(a.adsystem){var c=trb.data.ads&&trb.data.ads.options;var g=2;b+="\x26cw_pch\x3d1\x26ci_paic\x3d1\x26ci_pdic\x3d1\x26cw_pdpm\x3d"+encodeURIComponent(location.href);if("nguxdfp"==a.adsystem&&a.event){var h=
a.event,f=h.slot,k=h.size;a=null;b+="\x26adsystem\x3dnguxdfp\x26cw_pve\x3d1\x26cw_paduid\x3d"+encodeURIComponent(f.getAdUnitPath()||"")+"\x26cw_pdadvid\x3d"+(h.advertiserId||"")+"\x26cw_pdcrid\x3d"+(h.creativeId||"")+"\x26cw_pdadid\x3d"+(h.lineItemId||"")+"\x26cw_pdcid\x3d"+(h.campaignId||"")+"\x26emptyadresponse\x3d"+h.isEmpty+"\x26oopad\x3d"+!!f.isOop+"\x26adsize\x3d"+(k?k[0]+"x"+k[1]:"")+"\x26adtarss\x3d"+(f.getTargeting("ss")||"")+"\x26adtarpos\x3d"+(f.getTargeting("pos")||"")}c&&(b+="\x26adtaradb\x3d"+
(c.adb||"")+"\x26adtarexop\x3d"+(c.exop||""))}if(a)for(var l in a)a.hasOwnProperty(l)&&(b+="\x26"+l+"\x3d"+encodeURIComponent(a[l]||""));send(d,b,e,g||"3")},e=d.prop28||fssorid;!e&&trb.cookie.get("c_mId")&&trb.utils&&trb.utils.trySSORuser?trb.utils.trySSORuser(function(a){a&&a.isLoggedIn()&&(e=fssorid=a.getConsumerId());c()}):c()}}}};a&&"object"==typeof a&&a.forEach&&a.forEach(d.push)}))}})}},2083648,415301);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var t=window.trb&&trb.data&&trb.data.page&&trb.data.page.metrics&&trb.data.page.metrics.contentType,r=document.readyState,b=Bootstrapper;if(t)b.dtv=t.indexOf("video")>-1;if(r=="interactive")b.callOnDOMParsed();else if(r=="complete")b.callOnDOMLoaded()},1684605,393988);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();